### ISSUE TITLE
Support EXIF date format

### ISSUE THREAD

**Issue by ambs** [libwww-perl/HTTP-Date#19]
Not sure how possible this is. But it would be great if 2018:10:05 08:02:04 could be recognized.
I will need a workaround for my tool, as I need this working right now, but here is my wish :)

**Comment by karenetheridge** [comment]
recognized how? can you show an example?

HTTP::Date is just a date parser for one specific format; there are other date parsers, e.g. in DateTime::Format::*.

**Comment by ambs** [comment]
In fact in the documentation you have "The function is able to parse the following formats:"
so, I was asking a new one
   YYYY:MM:DD HH:MM:SS

Thanks

Alberto Simões

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by karenetheridge** [comment]
I think you should use DateTime::Format::ISO8601 or DateTime::Format::EXIF for that.  HTTP::Date is intended strictly for parsing dates found in HTTP headers, not as a generic datetime parsing tool.

**Comment by ambs** [comment]
OK. Fair enough. I did a workaround, anyway.
